global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - alerts.yml

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "api-gateway"
    metrics_path: /metrics
    static_configs:
      - targets: ["api-gateway:8999"]

  - job_name: "auth-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["auth-service:9091"]

  - job_name: "academic-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["academic-service:9092"]

  - job_name: "attendance-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["attendance-service:9093"]

  - job_name: "assessment-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["assessment-service:9094"]

  - job_name: "admission-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["admission-service:9095"]

  - job_name: "finance-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["finance-service:9096"]

  - job_name: "notification-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["notification-service:9097"]

  - job_name: "file-service"
    metrics_path: /metrics
    static_configs:
      - targets: ["file-service:9098"]
