image:
  repository: sisfo-akademik/admission-service
  tag: latest

service:
  port: 80
  targetPort: 9095

env:
  APP_ENV: "production"
  APP_SERVICE_NAME: "admission-service"
  APP_HTTP_PORT: "9095"
  APP_POSTGRES_URL: "postgres://user:pass@postgres:5432/admission_db?sslmode=disable"
  APP_REDIS_ADDR: "redis:6379"
  APP_RABBIT_URL: "amqp://user:pass@rabbitmq:5672/"

livenessProbe:
  httpGet:
    path: /health
    port: http
