image:
  repository: sisfo-akademik/attendance-service
  tag: latest

service:
  port: 80
  targetPort: 9093

env:
  APP_ENV: "production"
  APP_SERVICE_NAME: "attendance-service"
  APP_HTTP_PORT: "9093"
  APP_POSTGRES_URL: "postgres://user:pass@postgres:5432/attendance_db?sslmode=disable"
  APP_REDIS_ADDR: "redis:6379"
  APP_RABBIT_URL: "amqp://user:pass@rabbitmq:5672/"

livenessProbe:
  httpGet:
    path: /health
    port: http

autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 6
  targetCPUUtilizationPercentage: 70
  targetMemoryUtilizationPercentage: 75
