image:
  repository: sisfo-akademik/auth-service
  tag: latest

service:
  port: 80
  targetPort: 9091

env:
  APP_ENV: "production"
  APP_SERVICE_NAME: "auth-service"
  APP_HTTP_PORT: "9091"
  APP_POSTGRES_URL: "postgres://user:pass@postgres:5432/auth_db?sslmode=disable"
  APP_REDIS_ADDR: "redis:6379"
  APP_RABBIT_URL: "amqp://user:pass@rabbitmq:5672/"
  APP_JWT_ACCESS_SECRET: "changeme"
  APP_JWT_REFRESH_SECRET: "changeme"
  APP_JWT_ACCESS_EXPIRY: "15m"
  APP_JWT_REFRESH_EXPIRY: "168h"

livenessProbe:
  httpGet:
    path: /health
    port: http
