image:
  repository: sisfo-akademik/finance-service
  tag: latest

service:
  port: 80
  targetPort: 9096

env:
  APP_ENV: "production"
  APP_SERVICE_NAME: "finance-service"
  APP_HTTP_PORT: "9096"
  APP_POSTGRES_URL: "postgres://user:pass@postgres:5432/finance_db?sslmode=disable"
  APP_REDIS_ADDR: "redis:6379"
  APP_RABBIT_URL: "amqp://user:pass@rabbitmq:5672/"

livenessProbe:
  httpGet:
    path: /health
    port: http
